name: main
on:
  push:
    branches:
      - "**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v3.0.0

  small-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install jobsim
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: run large-tests
        run: pytest -s -v tests/small

  large-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install jobsim
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: run large-tests
        run: pytest -s -v tests/large
