name: main
on:
  push:
    branches:
      - "**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v3.0.0

  small-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install jobsim
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: run small-tests
        run: poetry run pytest -s -v tests/small

  report_jobs_results:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - small-tests
    steps:
      - uses: uoboda-splunk/workflow-info-splunk-upload-action@v1
        with:
          repository: ${{ github.repository }}
          run_id: ${{ github.run_id }}
          user: ${{ github.actor }}
          splunk_host: ${{ secrets.SPLUNK_HOST }}
          splunk_token: ${{ secrets.SPLUNK_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
